$env:PHOENIX_ROUTE_PROVIDER = "ollama"
$env:PHOENIX_ROUTE_MODEL = "qwen2.5:latest"
$env:PHOENIX_ROUTE_GENOME = "AGATGGATACCTTACCTATGCCTTAAGTCTCGGCCCAGCACAGGTGATTCAGGCTTCGCCGATC"
Write-Host "PhoenixDNA route policy applied"